# Лабораторная работа №1. Методы сортировки
## Выполнила студентка группы БФИ1902 Мухина Марина Михайловна
## Задание №1
Описание условия задания:
1. Создать Jupyter Notebook со следующим наименованием: Lab1_Группа_ФИО
2. Создать новую ячейку с помощью кнопки
3. В созданной ячейке по указанной ниже форме заполните оглавление файла, заменив наименование группы и вписав све ФИО, после чего создайте еще одну ячейку и напишите следующий код:
4. С помощью кнопки запустите выполнение всех ячеек
5. После выполнения у вас должна отформатироваться ячейка с оглавлением и должен выполниться “Hello, World!”

In [ ]:
print("Hello, World!")

## Задание №2
Описание условия задания:  
Написать генератор случайных матриц(многомерных), который принимает опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер матрицы, а min_lim и max_lim - минимальное и максимальное значение для генерируемого числа . По умолчанию при отсутствии параметров принимать следующие значения:  
m = 50  
n = 50  
min_limit = -250  
max_limit = 1000 + (номер своего варианта, у меня 12)  

In [2]:
import random
import numpy
m = 50
n = 50
min_limit = -250
max_limit = 1012
strM = input("Введите строки: ")
if len(strM) > 0: m = int(strM)
strN = input("Введите стобцы: ")
if len(strN) > 0: n = int(strN)
while True:
    strMin_limit = input("Введите минимальное значение: ")
    if len(strMin_limit) > 0: min_limit = int(strMin_limit)
    strMax_limit = input("Введите максимальное значение: ")
    if len(strMax_limit) > 0: max_limit = int(strMax_limit)
    if min_limit <= max_limit:
        break
    else:
        print("\nМинимальный элемент не может быть больше максимального, повторите попытку\n")
# Создание матрицы
array = numpy.zeros((m, n))
# Заполнение матрицы
for i in range(m):
    for j in range(n):
        array[i][j] = random.randint(int(min_limit), int(max_limit))
print("Матрица сгенерирована: ")
print(array)

Введите строки: 6
Введите стобцы: 6
Введите минимальное значение: 1
Введите максимальное значение: 8
Матрица сгенерирована: 
[[4. 5. 6. 2. 8. 7.]
 [5. 5. 8. 8. 2. 3.]
 [2. 8. 8. 3. 2. 8.]
 [3. 6. 6. 1. 8. 5.]
 [5. 7. 8. 5. 1. 4.]
 [1. 6. 5. 4. 4. 1.]]


## Задание №3
Описание условия задания:  
Реализовать методы сортировки строк числовой матрицы в соответствии с заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со временем стандартной функции сортировки. Испытания проводить на сгенерированных матрицах  
Методы:  
| Выбором | Вставкой | Обменом | Шелла | Турнирная | Быстрая сортировка | Пирамидальная | 

In [11]:
import timeit
import random
import numpy


# Сортировка выбором
def SelectionSort(arr):
    new_array = arr.copy()
    for i in range(m):
        for j in range(n - 1):
            min = j
            for h in range(j + 1, n):
                if new_array[i][h] < new_array[i][min]:
                    min = h
            temp = new_array[i][j]
            new_array[i][j] = new_array[i][min]
            new_array[i][min] = temp
    return new_array


# Сортировка вставкой
def InsertionSort(arr):
    array = arr.copy()
    for i in range(len(array)):
        for j in range(len(array[i])):
            temp = array[i][j]
            index = j
            while (temp < array[i][index - 1]) and (index > 0):
                array[i][index] = array[i][index - 1]
                index -= 1
            array[i][index] = temp
    return array


# Сортировка обменом
def BubbleSort(arr):
    array = arr.copy()
    for i in range(len(array)):
        for j in range(len(array[i])):
            for h in range(len(array[i]) - j - 1):
                if array[i][h + 1] < array[i][h]:
                    temp = array[i][h]
                    array[i][h] = array[i][h + 1]
                    array[i][h + 1] = temp
    return array


# Сортировка Шелла¶
def ShellSort(arr):
    array = arr.copy()
    for i in range(len(array)):
        d = int(len(array[i]) / 2)
        while d > 0:
            for j in range(len(array[i])):
                for h in range(int(j + d), len(array[i]), d):
                    if array[i][j] > array[i][h]:
                        temp = array[i][j]
                        array[i][j] = array[i][h]
                        array[i][h] = temp

            d = int(d / 2)
    return array


# Сортировка Турнирная
def TournamentSort(array):
    arr = array.copy()
    for i in range(len(arr)):
        tournamentSort(arr[i])
    return arr


def tournamentSort(arr):
    tree = [None] * 2 * (len(arr) + len(arr) % 2)
    index = len(tree) - len(arr) - len(arr) % 2

    for i, v in enumerate(arr):
        tree[index + i] = (i, v)

    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1)
                if tree[i] is not None and tree[i + 1] is not None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] is not None else tree[i + 1]
            index -= n

        index, x = tree[0]
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr) % 2 + index] = None

 
    
# Сортировка Быстрая
def QuickSort(array):
    arr = array.copy()
    for i in range(len(arr)):
        quickSort(0, len(arr[i]) - 1, arr, i)
    return arr


def quickSort(_first, _last, array, row):
    first = int(_first)
    last = int(_last)
    middle = int((first + last) / 2)

    while first < last:

        while array[row][first] < array[row][middle]:
            first += 1
        while array[row][last] > array[row][middle]:
            last -= 1
        if first <= last:
            array[row][first], array[row][last] = array[row][last], array[row][first]
            first += 1
            last -= 1

    if _first < last:
        quickSort(_first, last, array, row)
    if first < _last:
        quickSort(first, _last, array, row)


# Сортировка Пирамидальная
def heapify(arr, n, i):
    largest = i
    l = 2 * i + 1
    r = 2 * i + 2

    if l < n and arr[i] < arr[l]:
        largest = l

    if r < n and arr[largest] < arr[r]:
        largest = r

    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]

        heapify(arr, n, largest)


def HeapSort(array):
    arr = array.copy()
    for i in range(len(arr)):
        n = len(arr[i])

        for j in range(n, -1, -1):
            heapify(arr[i], n, j)

        for j in range(n - 1, 0, -1):
            arr[i][j], arr[i][0] = arr[i][0], arr[i][j]
            heapify(arr[i], j, 0)
    return arr


m = 50
n = 50
min_limit = -250
max_limit = 1012
strM = input("Введите строки: ")
if len(strM) > 0: m = int(strM)
strN = input("Введите стобцы: ")
if len(strN) > 0: n = int(strN)
while True:
    strMin_limit = input("Введите минимальное значение: ")
    if len(strMin_limit) > 0: min_limit = int(strMin_limit)
    strMax_limit = input("Введите максимальное значение: ")
    if len(strMax_limit) > 0: max_limit = int(strMax_limit)
    if min_limit <= max_limit:
        break
    else:
        print("\nМинимальный элемент не может быть больше максимального, повторите попытку\n")
# Создание матрицы
array = numpy.zeros((m, n))
# Заполнение матрицы
for i in range(m):
    for j in range(n):
        array[i][j] = random.randint(int(min_limit), int(max_limit))
print("Матрица сгенерирована: ")
print(array)

print("Время работы сортировки выбором: ")
start_time = timeit.default_timer()
print(SelectionSort(array))
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Время работы сортировки вставкой: ")
start_time = timeit.default_timer()
print(InsertionSort(array))
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Время работы сортировки обменом: ")
start_time = timeit.default_timer()
print(BubbleSort(array))
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Время работы сортировки Шелла: ")
start_time = timeit.default_timer()
print(ShellSort(array))
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Время работы сортировки Турнирной: ")
start_time = timeit.default_timer()
print(TournamentSort(array))
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Время работы сортировки Быстрой: ")
start_time = timeit.default_timer()
print(QuickSort(array))
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Время работы сортировки Пирамидальной: ")
start_time = timeit.default_timer()
print(HeapSort(array))
time_2 = timeit.default_timer() - start_time
print(time_2)

Введите строки: 8
Введите стобцы: 8
Введите минимальное значение: 1
Введите максимальное значение: 9
Матрица сгенерирована: 
[[1. 3. 9. 6. 7. 7. 8. 1.]
 [4. 9. 9. 2. 8. 2. 4. 6.]
 [9. 1. 1. 3. 7. 3. 2. 2.]
 [9. 7. 3. 8. 6. 8. 7. 2.]
 [7. 2. 3. 5. 6. 1. 5. 8.]
 [9. 2. 4. 5. 2. 4. 7. 7.]
 [7. 2. 6. 6. 2. 9. 5. 9.]
 [2. 1. 9. 1. 2. 8. 4. 6.]]
Время работы сортировки выбором: 
[[1. 1. 3. 6. 7. 7. 8. 9.]
 [2. 2. 4. 4. 6. 8. 9. 9.]
 [1. 1. 2. 2. 3. 3. 7. 9.]
 [2. 3. 6. 7. 7. 8. 8. 9.]
 [1. 2. 3. 5. 5. 6. 7. 8.]
 [2. 2. 4. 4. 5. 7. 7. 9.]
 [2. 2. 5. 6. 6. 7. 9. 9.]
 [1. 1. 2. 2. 4. 6. 8. 9.]]
0.001447699999971519
Время работы сортировки вставкой: 
[[1. 1. 3. 6. 7. 7. 8. 9.]
 [2. 2. 4. 4. 6. 8. 9. 9.]
 [1. 1. 2. 2. 3. 3. 7. 9.]
 [2. 3. 6. 7. 7. 8. 8. 9.]
 [1. 2. 3. 5. 5. 6. 7. 8.]
 [2. 2. 4. 4. 5. 7. 7. 9.]
 [2. 2. 5. 6. 6. 7. 9. 9.]
 [1. 1. 2. 2. 4. 6. 8. 9.]]
0.0007419999999456195
Время работы сортировки обменом: 
[[1. 1. 3. 6. 7. 7. 8. 9.]
 [2. 2. 4. 4. 6. 8. 9. 9.]
 [1. 1. 2. 2. 3. 3. 7. 9

## Задание №4
Создать публичный репозиторий на github, и запушить выполненное задание в
.ipynb формате.

## Вывод: 
В данной лараторной работе мы познакомились и научились работать с основными алгоритмами сортировки